version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    target-branch: main
  - package-ecosystem: npm
    directory: "/functions"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    target-branch: main
